'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace Solution


	Partial Public Class [Default]
		Inherits System.Web.UI.Page

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' grid control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected grid As Global.DevExpress.Web.ASPxGridView

		''' <summary>
		''' rblDatasources control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected rblDatasources As Global.DevExpress.Web.ASPxRadioButtonList

		''' <summary>
		''' dsProducts control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected dsProducts As System.Web.UI.WebControls.AccessDataSource

		''' <summary>
		''' dsCategories control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected dsCategories As System.Web.UI.WebControls.AccessDataSource

		''' <summary>
		''' dsShippers control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected dsShippers As System.Web.UI.WebControls.AccessDataSource
	End Class
End Namespace
